version: '3.8'
services:
  stats-server:
    build: ./server-stats/service
    image: stats_service
    container_name: stats_service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server-ewm
    image: ewm_service
    container_name: ewm_service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=root
